---
title: "models"
output: html_document
---


```{r setup, include=FALSE}

if(!require("pacman")) install.packages("pacman"); library(pacman)
p_load("tidyverse", "here", "readr", "lattice", "hexbin", "stargazer", "lme4", 
          "gridExtra", "stringr", "Hmisc","psych", "scales", "workflowr",
          "readxl", "vioplot", "expss", "jtools", "broom", "kableExtra", "knitr",
          "sjlabelled", "naniar", "summarytools", "GGally", "correlation", "dplyr", "janitor", "ggplot2", 'rio','survey', 'parsedate','sjPlot', 'sjmisc', "scales", "reshape2", "skimr", "kableExtra","testthat", "patchwork", "tidyr", "utils", "tidybayes", "ggalt", "ggstance", "ISLR", "rstanarm", "brms", "standardize", "mctest", "car", "pls", "corrplot", "corrgram", "wesanderson", "huxtable", "arm", "ggpubr")


source(here('code/functions.R'))

knitr.table.format = "html"
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

```


```{r load and filter data, include=FALSE, echo=FALSE}
dat_path_1 <-
  here("data/tracking_survey_w1_public.csv")
data_1 <- read.csv(dat_path_1) %>%
  filter(consent == 5) %>%
  filter(Finished == 1) %>%
  filter(age > 17) %>%
  filter(attention_check == 1) %>%
  rename (id = X,
          reduce_lik_mild = participant_benefit)
colnames(data_1)
dim(data_1)

dat_path_2 <-
  here("data/tracking_survey_w2_public.csv")
data_2 <- read.csv(dat_path_2) %>%
  filter(consent == 5) %>%
  filter(Finished == 1) %>%
  filter(age > 17) %>%
  filter(attention_check == 1 | att_check_bt == 1) %>%
  rename (id = X)
colnames(data_2)
dim(data_2)

dat_path_3 <-
  here("data/tracking_survey_w3_public.csv")
data_3 <- read.csv(dat_path_3) %>%
  filter(consent == 5) %>%
  filter(Finished == 1) %>%
  filter(age > 17) %>%
  filter(attention_check == 1) %>%
  rename (id = X)
colnames(data_3)
dim(data_3)

dat_path_4 <-
  here("data/tracking_survey_w4_public.csv")
data_4 <- read.csv(dat_path_4) %>%
  filter(consent == 5) %>%
  filter(Finished == 1) %>%
  filter(age > 17) %>%
  filter(attention_check == 1) %>%
  rename (id = X)
colnames(data_4)
dim(data_4)



```
## Regression models


Wave 3 - prepare variables

```{r, wave 3 covariates}

mod3_data <- data_3 %>% dplyr::select(
  c(
    contains("wv"),
    contains("Conspir"),
    trust_intentions_bt,
    trust_respectpriv_bt,
    data_security_bt,
    starts_with('sci'),
    starts_with('acc_general_'),
    COVID_sev_general,
    COVID_pers_harm,
    COVID_pers_concern,
    COVID_concern4others,
    age,
    education,
    gender,
    COVID_govresponse_3,
    Gov_helpful,
    RKI_future_download,
    risk_of_harm_bt,
    proportionality_bt,
    data_security_bt,
    reduce_lik_bt,
    return_activ_fut,
    reduce_spread_fut,
    COVID_info_source_6,
    COVID_info_trust_6,
    COVID_info_source_2,
    COVID_info_trust_2
  )
) %>%
  dplyr::filter(gender < 3) %>%
  drop_na


acceptability <-
  mod3_data %>% dplyr::select(starts_with('acc_general_'))
Acceptability <-
  revscore(acceptability, 4) %>% apply(., 1, mean, trim = .2, na.rm = TRUE)


Libertarianism <-
  mod3_data %>% dplyr::select(c(wv_freemarket_best, wv_freemarket_lim, wv_lim_gov)) %>% mutate(wv_freemarket_lim_rev = revscore(wv_freemarket_lim, 7)) %>%
  dplyr::select(-wv_freemarket_lim) %>% apply(., 1, mean, na.rm = TRUE)


COVIDrisk <-
  mod3_data %>% dplyr::select(c(
    COVID_sev_general,
    COVID_pers_harm,
    COVID_pers_concern,
    COVID_concern4others
  )) %>% apply(., 1, mean, na.rm = TRUE)
# 1 - sehr schwach

Govguidelines_helpful <-
  mod3_data %>% dplyr::select(Gov_helpful) %>% apply(., 1, mean, na.rm = TRUE)
# 1 = Gar nicht hilfreich

COVID_govresponse =  revscore(mod3_data$COVID_govresponse_3, 5) # 1 = extrem gut (reverse to 1 = gar nicht gut)
Germany_handling_thepandemic <- COVID_govresponse



Conspiracism <- mod3_data %>% dplyr::select(contains("Conspir")) %>%
  mutate(Conspir_4 = revscore(Conspir_4_REV, 5)) %>%
  dplyr::select(-Conspir_4_REV) %>%
  apply(., 1, mean, na.rm = TRUE)


# 1 = Falsch

Scitech_positive <-
  mod3_data  %>% dplyr::select(starts_with('sci')) %>%
  apply(., 1, mean, na.rm = TRUE)
# 1 - stimme nicht zu

#Education is recoded like this (None = 1, Real- and Haupt-schule = 2, Abitur = 3, Uni = 4 )
Education_recode = dplyr::recode(
  mod3_data$education,
  `4` = "low",
  `1` = "low",
  `2` = "low",
  `3` = "medium",
  `5` = "high",
  .default = NULL
)
Education <-
  factor(Education_recode,
         ordered = TRUE,
         levels = c("low", "medium", "high"))



CWA_future_download <-  mod3_data$RKI_future_download

Trust_appsecurity <-
  mod3_data %>% dplyr::select(starts_with("trust"), proportionality_bt,  data_security_bt) %>% apply(., 1, mean, na.rm =
                                                                                                       TRUE)

CWA_effectiveness <-
  mod3_data %>% dplyr::select(reduce_lik_bt, return_activ_fut, reduce_spread_fut) %>% apply(., 1, mean, na.rm =
                                                                                              TRUE)

Risk_of_harm <- mod3_data$risk_of_harm_bt



Gender_recode_male = dplyr::recode(
  mod3_data$gender,
  `1` = 1,
  `2` = 0,
  `3` = 0,
  .default = NULL
)
Gender_male <- Gender_recode_male

Age <- mod3_data$age

Socialmedia_source_and_trust <-
  mod3_data %>% dplyr::select(COVID_info_source_2, COVID_info_trust_2) %>% apply(., 1, mean, na.rm =
                                                                                   TRUE)

Govannouncements_source_and_trust <-
  mod3_data %>% dplyr::select(COVID_info_source_6, COVID_info_trust_6) %>% apply(., 1, mean, na.rm =
                                                                                   TRUE)


model_data3 <-
  as.data.frame(
    cbind(
      CWA_future_download,
      Acceptability,
      Libertarianism,
      Conspiracism,
      Scitech_positive,
      COVIDrisk,
      Govguidelines_helpful,
      Trust_appsecurity,
      Risk_of_harm,
      Education,
      Age,
      CWA_effectiveness,
      Germany_handling_thepandemic,
      Socialmedia_source_and_trust,
      Govannouncements_source_and_trust,
      Gender_male
    )
  ) %>% mutate(Education = factor(
    Education,
    ordered = FALSE,
    levels = c(2, 1, 3),
    labels = c("medium", "low", "high")
  ))

contrasts(model_data3$Education) <-
  contr.treatment(levels(model_data3$Education))

```
Wave 4 - prepare variables

```{r, wave 4 covariates}



mod4_data <- data_4 %>% dplyr::select(
  c(
    contains("wv"),
    contains("Conspir"),
    starts_with("trust"),
    starts_with('sci'),
    starts_with('acc_general_'),
    COVID_sev_general,
    COVID_pers_harm,
    COVID_pers_concern,
    COVID_concern4others,
    age,
    education,
    gender,
    COVID_govresponse_3,
    Gov_helpful,
    RKI_future_download,
    risk_of_harm_bt,
    proportionality_bt,
    data_security_bt,
    reduce_lik_bt,
    return_activ_fut,
    reduce_spread_fut,
    COVID_info_source_6,
    COVID_info_trust_6,
    COVID_info_source_2,
    COVID_info_trust_2
  )
) %>%
  dplyr::filter(gender < 3) %>%
  drop_na


# Sehr akzeptabel (1)	Einigermaßen akzeptabel (2) need to revscore

acceptability <-
  mod4_data %>% dplyr::select(starts_with('acc_general_'))
Acceptability <-
  revscore(acceptability, 4) %>% apply(., 1, mean, trim = .2, na.rm = TRUE)


Libertarianism <-
  mod4_data %>% dplyr::select(c(wv_freemarket_best, wv_freemarket_lim, wv_lim_gov)) %>% mutate(wv_freemarket_lim_rev = revscore(wv_freemarket_lim, 7)) %>%
  dplyr::select(-wv_freemarket_lim) %>% apply(., 1, mean, na.rm = TRUE)


COVIDrisk <-
  mod4_data %>% dplyr::select(c(
    COVID_sev_general,
    COVID_pers_harm,
    COVID_pers_concern,
    COVID_concern4others
  )) %>% apply(., 1, mean, na.rm = TRUE)



Govguidelines_helpful <-
  mod4_data  %>% dplyr::select(Gov_helpful) %>% apply(., 1, mean, na.rm = TRUE)

COVID_govresponse4 = revscore(mod4_data$COVID_govresponse_3, 5) # 1 = extrem gut (reverse to 1 = gar nicht gut)
Germany_handling_thepandemic <-
  COVID_govresponse4


Conspiracism <-
  mod4_data  %>% dplyr::select(contains("Conspir")) %>%
  mutate(Conspir_6 = revscore(Conspir_6_rev, 5)) %>%
  dplyr::select(-Conspir_6_rev) %>%
  apply(., 1, mean, trim = .2, na.rm = TRUE)


Scitech_positive <-
  mod4_data  %>% dplyr::select(starts_with('sci')) %>%
  apply(., 1, mean, na.rm = TRUE)

# recode eductaion to group categories into none (4 --> 1), low(real (1) and haupt-schule (2) --> 2), medium (abitur=3), and high(uni=5 --> 4)
Education_recode = dplyr::recode(
  mod4_data$education,
  `4` = "low",
  `1` = "low",
  `2` = "low",
  `3` = "medium",
  `5` = "high",
  .default = NULL
)
Education <-
  factor(Education_recode,
         ordered = TRUE,
         levels = c("low", "medium", "high"))


CWA_future_download <- mod4_data$RKI_future_download

Trust_appsecurity <-
  mod4_data %>% dplyr::select(starts_with("trust"), proportionality_bt, data_security_bt) %>% apply(., 1, mean, na.rm =
                                                                                                      TRUE)

CWA_effectiveness <-
  mod4_data %>% dplyr::select(reduce_lik_bt, return_activ_fut, reduce_spread_fut) %>% apply(., 1, mean, na.rm =
                                                                                              TRUE)

Risk_of_harm <- mod4_data$risk_of_harm_bt


Socialmedia_source_and_trust <-
  mod4_data %>% dplyr::select(COVID_info_source_2, COVID_info_trust_2) %>% apply(., 1, mean, na.rm =
                                                                                   TRUE)

Govannouncements_source_and_trust <-
  mod4_data %>% dplyr::select(COVID_info_source_6, COVID_info_trust_6) %>% apply(., 1, mean, na.rm =
                                                                                   TRUE)

Gender_recode_male = dplyr::recode(mod4_data$gender,
                                   `1` = 1,
                                   `2` = 0,
                                   .default = NULL)
Gender_male <- Gender_recode_male

Age <- mod4_data$age


model_data4 <-
  as.data.frame(
    cbind(
      CWA_future_download,
      Acceptability,
      Libertarianism,
      Conspiracism,
      Scitech_positive,
      COVIDrisk,
      Govguidelines_helpful,
      Trust_appsecurity,
      Risk_of_harm,
      Education,
      Age,
      CWA_effectiveness,
      Germany_handling_thepandemic,
      Socialmedia_source_and_trust,
      Govannouncements_source_and_trust,
      Gender_male
    )
  ) %>% mutate(Education = factor(
    Education,
    ordered = FALSE,
    levels = c(2, 1, 3),
    labels = c("medium", "low", "high")
  ))

contrasts(model_data4$Education) <-
  contr.treatment(levels(model_data4$Education))




```




GLM (logistic regression): predictors for CWA download (intentions)




```{r, logistic regression for CWA downloads}




glm3f <-
  glm(
    CWA_future_download ~  Trust_appsecurity + CWA_effectiveness + Acceptability +  Germany_handling_thepandemic + Govguidelines_helpful + Socialmedia_source_and_trust + Govannouncements_source_and_trust + Conspiracism + Libertarianism + COVIDrisk + Scitech_positive +  Gender_male + Age + Risk_of_harm + Education,
    data = model_data3,
    family = "binomial"
  )

glm4f <-
  glm(
    CWA_future_download ~  Trust_appsecurity + CWA_effectiveness + Acceptability +  Germany_handling_thepandemic + Govguidelines_helpful + Socialmedia_source_and_trust + Govannouncements_source_and_trust + Conspiracism + Libertarianism + COVIDrisk + Scitech_positive +  Gender_male + Age + Risk_of_harm + Education,
    data = model_data4,
    family = "binomial"
  )

glm3f_s <- standardize(
  glm3f,
  unchanged = "Education",
  standardize.y = FALSE,
  binary.inputs = "center"
)
display(glm3f_s)

glm4f_s <- standardize(
  glm4f,
  unchanged = "Education",
  standardize.y = FALSE,
  binary.inputs = "center"
)
display(glm4f_s)


mr_plot_intentions <-
  plot_summs(
    glm3f_s,
    glm4f_s,
    colors = c("cornflowerblue", "#4cbc7c"),
    legend.title = "Wave",
    model.names = c("Wave 3", "Wave 4"),
    coefs = c(
      "Trust in CWA security" = "z.Trust_appsecurity",
      "Perception of CWA effectiveness" = "z.CWA_effectiveness",
      "Acceptance of privacy limits" = "z.Acceptability",
      "COVID-19 risk perception" = "z.COVIDrisk",
      "Belief in conspiracies" = "z.Conspiracism",
      "Social media use & trust" = "z.Socialmedia_source_and_trust",
      "Government announcements use & trust" =
        "z.Govannouncements_source_and_trust",
      "Approval of German pandemic response" =
        "z.Germany_handling_thepandemic",
      "Find government guidelines helpful" =
        "z.Govguidelines_helpful",
      "Attitudes to science and technology" = "z.Scitech_positive",
      "Libertarianism" = "z.Libertarianism",
      "CWA risk of harm perception" = "z.Risk_of_harm",
      "Age" = "z.Age",
      "Gender: male (vs. female)" = "c.Gender_male",
      "Education: low (vs. medium)" = "Educationlow",
      "Education: high  (vs. medium)" = "Educationhigh"
    )
  ) +
  # xlim(0, 2.5) +
  theme_nice() +
  labs(title = "Predictors of intention to download Corona-Warn-App", y = "")
mr_plot_intentions


ggsave(
  filename = here("output/mr_plot_intentions.pdf"),
  plot = mr_plot_intentions,
  dpi = 300,
  units = 'cm',
  height = 20,
  width = 26
)


stargazer(
  glm3f_s,
  glm4f_s,
  title = "Regression Results",
  align = TRUE,
  dep.var.labels = c("CWA intention to download"),
  covariate.labels = c(
    "Trust in CWA security",
    "Perception of CWA effectiveness",
    "Acceptance of privacy limits",
    "Approval of German pandemic response",
    "Find government guidelines helpful",
    "Social media use and trust",
    "Government announcements use and trust",
    "Belief in conspiracies",
    "Libertarianism",
    "COVID-19 risk perception",
    "Attitudes to science and technology",
    "Gender: male (vs. female)",
    "Age",
    "CWA risk of harm perception",
    "Education: low (vs. medium)",
    "Education: high  (vs. medium)"
  ),
  column.labels = c("Wave 3", "Wave 4"),
  ci = TRUE,
  ci.level = 0.95,
  no.space = TRUE,
  star.cutoffs = NA,
  omit.table.layout = "n"
)


```

Intentions - faceted


```{r, logistic regression for CWA downloads (intention)}



mr_plot_intentions_w3 <-
  plot_summs(
    glm3f_s,
    
    colors = c("cornflowerblue"),
    legend.title = "Wave",
    model.names = c("Wave 3"),
    coefs = c(
      "Trust in CWA security" = "z.Trust_appsecurity",
      "Perception of CWA effectiveness" = "z.CWA_effectiveness",
      "Acceptance of privacy limits" = "z.Acceptability",
      "COVID-19 risk perception" = "z.COVIDrisk",
      "Belief in conspiracies" = "z.Conspiracism",
      "Social media use & trust" = "z.Socialmedia_source_and_trust",
      "Government announcements use & trust" =
        "z.Govannouncements_source_and_trust",
      "Approval of German pandemic response" =
        "z.Germany_handling_thepandemic",
      "Find government guidelines helpful" =
        "z.Govguidelines_helpful",
      "Attitudes to science and technology" = "z.Scitech_positive",
      "Libertarianism" = "z.Libertarianism",
      "CWA risk of harm perception" = "z.Risk_of_harm",
      "Age" = "z.Age",
      "Gender: male (vs. female)" = "c.Gender_male",
      "Education: low (vs. medium)" = "Educationlow",
      "Education: high  (vs. medium)" = "Educationhigh"
    )
  ) +
  theme_nice() +
  theme(axis.title.y = element_blank()) +
  labs(title = "Predictors of intention to download CWA: Wave 3", y = "")
mr_plot_intentions_w3


mr_plot_intentions_w4 <-
  plot_summs(
    glm4f_s,
    colors = c("#4cbc7c"),
    legend.title = "Wave",
    model.names = c("Wave 4"),
    coefs = c(
      "Trust in CWA security" = "z.Trust_appsecurity",
      "Perception of CWA effectiveness" = "z.CWA_effectiveness",
      "Acceptance of privacy limits" = "z.Acceptability",
      "COVID-19 risk perception" = "z.COVIDrisk",
      "Belief in conspiracies" = "z.Conspiracism",
      "Social media use & trust" = "z.Socialmedia_source_and_trust",
      "Government announcements use & trust" =
        "z.Govannouncements_source_and_trust",
      "Approval of German pandemic response" =
        "z.Germany_handling_thepandemic",
      "Find government guidelines helpful" =
        "z.Govguidelines_helpful",
      "Attitudes to science and technology" = "z.Scitech_positive",
      "Libertarianism" = "z.Libertarianism",
      "CWA risk of harm perception" = "z.Risk_of_harm",
      "Age" = "z.Age",
      "Gender: male (vs. female)" = "c.Gender_male",
      "Education: low (vs. medium)" = "Educationlow",
      "Education: high  (vs. medium)" = "Educationhigh"
    )
  ) +
  theme_nice() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank()) +
  labs(title = "Wave 4", y = "")
mr_plot_intentions_w4


mr_plot_int_comb <-
  ggarrange(mr_plot_intentions_w3, mr_plot_intentions_w4, widths = c(1, 0.8))
mr_plot_int_comb


ggsave(
  filename = here("output/mr_plot_intentions_faceted.pdf"),
  plot = mr_plot_int_comb,
  dpi = 300,
  units = 'cm',
  height = 20,
  width = 34
)





```
