---
title: "Supplement Information"
date: "Initial upload: 07/12/2020"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
    theme: spacelab
    highlight: textmate

---


```{r setup, include=FALSE, message = FALSE, warning = FALSE}
if(!require("pacman")) install.packages("pacman"); library(pacman)
p_load("tidyverse", "here", "readr", 
          "kableExtra", "knitr", "workflowr")
knitr.table.format = "html"
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```


## Tracking technologies scenarios and Corona-Warn-App vingette

```{r, echo=FALSE}
scenarios <- data.frame(
  Scenario =c("Severe",
              "Mild", 
              "Bluetooth",
              "Corona-Warn-App"),
  Description=c("The COVID-19 pandemic has rapidly become a worldwide threat. Containing the virus' spread is essential to minimise the impact on the healthcare system, the economy, and save many lives. The Government might consider using phone tracking data supplied by telecommunication companies to identify and contact those who may have been exposed to people with COVID-19. This would help reduce community spread by identifying those most at risk and allowing health services to be appropriately targeted. All people using a mobile phone would be included in the project, with no possibility to opt-out. Data would be stored in an encrypted format on a secure server accessible only to the Government which may use the data to locate people who were violating lockdown orders and enforce them with fines and arrests where necessary. Data would also be used to inform the appropriate public health response and to contact those who might have been exposed to COVID-19. Individual quarantine orders could be made on the basis of this data.",
                "The COVID-19 pandemic has rapidly become a worldwide threat. Containing the virus' spread is essential to minimise the impact on the healthcare system, the economy, and save many lives. The Government might consider using smartphone tracking data to identify and contact those who may have been exposed to people with COVID-19. This would help reduce community spread by identifying those most at risk and allowing health services to be appropriately targeted. Only people who downloaded a government app and agreed to be tracked and contacted would be included in the project. The more people download and use this app, the more effectively the Government would be able to contain the spread of COVID-19. Data would be stored in an encrypted format on a secure server accessible only to the Government. Data would only be used to contact those who might have been exposed to COVID-19.",
              "The COVID-19 pandemic has rapidly become a worldwide threat. Containing the virus’ spread is essential to minimise the impact on the healthcare system, the economy, and save many lives. Apple and Google have proposed adding a contact tracing capability to existing smartphones to help inform people if they have been exposed to others with COVID-19. This would help reduce community spread of COVID-19 by allowing people to voluntarily self-isolate.  When two people are near each other, their phones would connect via bluetooth. If a person is later identified as being infected, the people they have been in close proximity to are then notified without the government knowing who they are. The use of this contact tracing capability would be completely voluntary. People who are notified would not be informed who had tested positive.",
              "Die Corona-Warn-App soll dabei helfen, Infektionsketten frühzeitig zu erkennen und zu durchbrechen. Aktuell bemühen sich die Mitarbeiter:innen der Gesundheitsämter, Infektionsketten nachzuverfolgen. Mit der App könnte das automatisiert und damit viel schneller und genauer geschehen. Nutzer:innen können umgehend gewarnt werden, wenn sie sich in der Nähe von infizierten Personen aufgehalten haben. 
Die App wurde von der Deutschen Telekom und SAP entwickelt und vom Robert Koch-Institut herausgegeben. Sie erfasst, welche Smartphones einander nahe gekommen sind. Dazu tauschen die Geräte via Bluetooth zufällig erzeugte Krypto-Schlüssel aus. Auf Basis der Signalstärke wird dabei die Entfernung geschätzt. 
Werden Nutzer:innen positiv auf COVID-19 getestet, können sie das Testergebnis in der App teilen, damit Nutzer:innen, die sich in ihrer Nähe aufgehalten haben, informiert werden. Infizierte werden ausdrücklich gefragt, ob sie das Ergebnis zur Kontakt-Nachverfolgung teilen wollen. Alternativ zu der digitalen Übertragung steht eine Validierung über ein Call-Center der Telekom zur Verfügung. Alle 24 Stunden überprüft die App, ob man mit einer Person Kontakt hatte, die sich als infiziert in die App eingetragen hat.
Die App wertet keine Geo-Daten aus und übermittelt keine Ortsinformationen. Es erfolge auch kein Versand und keine Speicherung von personenbezogenen Daten, versichern die Entwickler. Die anonymisierten Daten der Kontakte werden nicht zentral gespeichert, sondern dezentral auf dem jeweiligen Smartphone. Der Abgleich, ob man einer infizierten Person begegnet ist, geschieht lokal auf dem Mobiltelefon. Es verlassen keine Daten zum Abgleich das Handy, so die Entwickler:innen. Nur die anonymisierte Liste wird zentral gespeichert und von den Smartphones regelmäßig abgerufen, um mögliche problematische Begegnungen zu identifizieren."),
  Wave=c("1,2",
              "1,2", 
              "2",
              "3,4"))

table <- scenarios %>%
  kbl() %>%
  kable_paper("striped", full_width = F, position = "left") 
table

```

## Items querying acceptability of tracking in 3 scenarios and Corona-Warn-App Downloads

```{r, echo=FALSE}

tracking <- data.frame(
  Scenario = c("Severe", "Severe","Severe", "Mild", "Mild","Mild", "Bluetooth","Bluetooth","Corona-Warn-App","Corona-Warn-App"),
  Question =c("Is the use of cell phone data for location tracking acceptable in this scenario?",
              "Would your decision change if the Government was required to delete the data and stop tracking after six months?", 
              "Would your final decision change if there was an option to opt out of data collection?",
              "If, as depicted in this scenario, the Government developed a tracking app to help reduce the spread of COVID-19, would you download and use it?",
              "Would your decision change if the government was required to delete the data and cease tracking after six months?",
              "Would your final decision change if data was only stored on your smartphone (not on government servers) and you had the ability to provide this data if you tested positive for COVID-19?",
              "If, as depicted in this scenario, Apple and Google added a COVID-19 contact tracing capability into smartphones, would you use it?",
              "Would your decision change if Apple and Google promised to delete all data and remove the contact tracing system after six months?",
              "Did you download the Corona-Warn-App?",
              "Will you download the Corona-Warn-App in the future?"),
  Label =c("Acceptability of the scenario", "With follow up: delete data", "With follow up: opt out", "Acceptability of the scenario", "With follow up: delete data", "With follow up: local data","Acceptability of the scenario", "With follow up: delete data", "CWA downloads", "With follow up: future downloads")
  )



 table <-tracking %>%
  kbl() %>%
  kable_paper("striped", full_width = F, position = "left") 
 table

 table_tracking <- tracking %>%
  kbl(format="latex",
       booktabs = TRUE,
    caption = "Items querying acceptability of tracking in 3 scenarios and Corona-Warn-App Downloads,  \\label{tab:tracking}",
    table.envir = "table*") %>% 
   kable_paper("striped", full_width = F, position = "left")

write_lines( table_tracking , here("output/tracking.tex"))


```
## Reasons not to download the Corona-Warn-App

```{r, echo=FALSE}

reasonsnot <- data.frame(
  Question =c("I am concerned about privacy.",
              "I don't trust the government.", 
              "I am worried about battery usage on my phone.",
              "I don't think it's going to be effective.",
              "I am worried about normalizing government tracking.",
              "I am concerned about civil liberties.",
              "I don't own a smart phone.",
              "My phone is too old to run the app.",
              "I am concerned about others gaining access to my data."),
  Label =c('Privacy concerns','Lack of Gov trust','Concerns: Battery usage',
            'Believe it is non-effective','Concerns: Normalising Gov tracking', 
            'Concerns: Civil liberties',
            "Don't own a smartphone", "Phone too old",
            "Concerns: 3rd party access")
  )

 table <- reasonsnot %>%
  kbl() %>%
  kable_paper("striped", full_width = F, position = "left") 
 table
 
 
 table_reasonsnot <- reasonsnot  %>%
  kbl(format="latex",
       booktabs = TRUE,
    caption = "Items querying reasons not to download the Corona-Warn-App (participants could choose any number of available options). \\label{tab:reasonsnot}",
    table.envir = "table*") %>% 
   kable_paper("striped", full_width = F, position = "left")
table_reasonsnot
write_lines(table_reasonsnot, here("output/table_reasonsnot.tex"))
```

## Variables for regression models

```{r, echo=FALSE}

models <- data.frame(
  Variable =c("CWA download",
  "Trust in CWA security", 
           "Perception of CWA efficiency",
           "CWA risk of harm perception",
           "Acceptance of privacy limits",
           "Social media use & trust",
           "Governement announcements use & trust",
           "Covid-19 risk perception",
           "Approval of German pandemic response",
           "Find governement guidelenes helpful",
           "Attitudes to science and tech",
           "Libertarianism",
  "Beliefs in conspiracies (wave 3)",
           "Beliefs in conspiracies (wave 4)",
           "Gender (male)",
           "Education",
           "Age"),
  Items =c("Did you download the Corona-Warn-App?",
  "Combined measure for 3 items:
  1. How much do you trust the government to use the Corona-Warn-App data only to deal with the COVID-19 pandemic? 
  2. How much do you trust that the Corona-Warn-App is able to ensure the privacy of each individual that uses it?
  3. How secure is the data that is collected by the Corona-Warn-App?", 
           "Combined measure for 3 items: 
1. How confident are you that the Corona-Warn-App will help you to maintain your normal activities in the future course of the pandemic?  
2. How confident are you that the Corona-Warn-App will reduce the spread of COVID-19? 
3. How likely do you think that the Corona-Warn-App will reduce your risk to get in contact with the COVID-19 virus?",
           "How serious is the risk of harm that could arise from the Corona-Warn-App?",
           "Combined measure for a question How acceptable is it for the government to take the following measures to limit the spread of the virus during the time of the COVID 19 pandemic? with 6 items:
 1.Provide access to the medical records of individual,
 2.Track the location of people using their cell phone data, 
 3.Enable temporary relaxation of data protection regulations,
 4.Collect data about personal contacts and interactions,
 5.Enforce people to use an app that notifies when those in quarantine leave the house,
 6.Collect data on the infection and immunity status of citizens.",
           "Combined measure for 2 items about social media: 
 1.How often do you rely on the following media to keep you informed about the developments surrounding the COVID-19 pandemic? 2. How do you rate the following sources? Do you think that the information on the COVID 19 pandemic is correct and trustworthy?",
           "Combined measure for 2 items about Goverenment announcements: 
  1.How often do you rely on the following media to keep you informed about the developments surrounding the COVID-19 pandemic? 2. How do you rate the following sources? Do you think that the information on the COVID 19 pandemic is correct and trustworthy?",
           "Combined measure for 4 items:
1. How severe do you think novel coronavirus (COVID-19) will be for the general population?,
2. How harmful would it be for your health if you were to become infected COVID-19?, 
3. How concerned are you that you might become infected with COVID-19?,
4. How concerned are you that somebody you know might become infected with COVID-19?",
           "How well overall do you think the Governments in the following countries have handled the COVID-19 pandemic? - Germany",
           "How helpful are the government guidelines in deciding how to act in relation to the COVID-19 pandemic?",
           "Combined measure for 2 items: 
  1. Science and technology are making our lives healthier, easier, and more comfortable
  2. Because of science and technology, there will be more opportunities for the next generation.",
           "Combined measure for 2 items: 
           1. An economic system based on free markets unrestrained by government interference automatically works best to meet human needs.
2. The government should interfere with the lives of citizens as little as possible.",
 "Combined measure for 5 items: 
 1. There are secret organizations that have great influence on political decisions.
 2. Most people do not see how much our lives are determined by plots hatched in secret.
 3. There are certain political circles with secret agendas that are very influential.
 4. Secret organizations can manipulate people psychologically so that they do not notice how their life is being controlled by others.
 5. Selfish interests have conspired to convince the public that COVID-19 is a major threat.",
           "Combined measure for 6 items: 
           1. The Coronavirus does not really exist, but is a myth created by some influential people or institutions.
2. The Coronavirus was created in a laboratory and deliberately released to achieve geopolitical or economic goals.
3. There is a link between 5G and the spread of the Coronavirus. 
4. The severity of the Coronavirus disease is overstated. The actual risk is not higher than that of a seasonal influenza. 
5. The government exaggerates the seriousness of the pandemic in order to divert attention from other problems within Germany. 6. The Coronavirus was created by pharmaceutical companies to benefit from the need for a vaccine.",
           "What gender do you identify with?",
           "Please indicate your highest level of education",
           "How old are you?"),
    Scale=c("Yes(1), No(0)",
      "6 point Likert scale, 1 = not at all, 6 = very", 
           "6 point Likert scale, 1 = not at all, 6 = very",
           "6 point Likert scale, 1 = not at all, 6 = very",
           "4 point Likert scale, 1 = not acceptable at all, 4 = very acceptable",
           "5 point Likert scale, 1 = never/not at all, 5 = always/completely",
           "5 point Likert scale, 1 = never/not at all, 5 = always/completely",
           "5 point Likert scale, 1 = not at all, 5 = extremely",
           "5 point Likert scale, 1 = not at all, 5 = extremely",
           "5 point Likert scale, 1 = not at all, 5 = extremely",
           "7 point Likert scale, 1 = strongly disagree, 7 = strongly agree",
           "7 point Likert scale, 1 = strongly disagree, 7 = strongly agree",
      "7 point Likert scale, 1 = strongly disagree, 7 = strongly agree",
           "5 point Likert scale, 1 = undoubtedly false 7 = undoubtedly true",
           "Male (1), female, other",
           "None (1), Hauptschule, Realschule, Abitur, University (5)",
           "Free numeric text entry")
  )


# Variables_data = c("RKI_download",
#   "trust_respectpriv_bt, trust_intentions_bt, data_security_bt", 
#            "reduce_lik_bt, return_activ_fut, reduce_spread_fut",
#            "risk_of_harm_bt",
#            "acc_general_1, acc_general_2, acc_general_3, acc_general_4, acc_general_5, acc_general_6",
#            "COVID_info_source_2, COVID_info_trust_2",
#            "COVID_info_source_6, COVID_info_trust_6",
#            "COVID_sev_general, COVID_pers_harm, COVID_pers_concern, COVID_concern4others",
#            "COVID_govresponse_3",
#            "Gov_helpful",
#            "sci_betterlives, sci_nextgenopp",
#            "wv_freemarket_best, wv_lim_gov",
#            "Wave 3: Conspir_1, Conspir_2, Conspir_3, Conspir_5;
#   Wave 4: Conspir_1, Conspir_2, Conspir_3, Conspir_4, Conspir_5, Conspir_7. Controls were excluded.",
#            "gender",
#            "education",
#            "age"),

 table <- models %>%
  kbl() %>%
  kable_paper("striped", full_width = F, position = "left") %>% 
   column_spec(1, bold = T)
 table
 
 
```

